ARTS: ARTS::Var::String Class Reference
ARTS::Var::String Class Reference
#include <autoarts.h>
Public Member Functions
String () noexcept
String (std::size_t i, void *x) noexcept
~String () noexcept
String (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
String & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::String
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1468 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::String::type = Group::String private
Definition at line 1469 of file autoarts.h.
Constructor & Destructor Documentation
String() [1/3]
ARTS::Var::String::String () inline noexcept
Definition at line 1473 of file autoarts.h.
String() [2/3]
ARTS::Var::String::String (std::size_t i, void * x) inline noexcept
Definition at line 1474 of file autoarts.h.
~String()
ARTS::Var::String::~String () inline noexcept
Definition at line 1475 of file autoarts.h.
References islast(), isnull(), and v.
String() [3/3]
ARTS::Var::String::String (const type & val) inline noexcept
Definition at line 1476 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::String::islast () const inline noexcept
Definition at line 1482 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_cia_dataReadFromCIA(), ARTS::AgendaMethod::abs_lines_per_speciesReadSplitCatalog(), ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::AgendaMethod::abs_lines_per_speciesWriteSplitXML(), ARTS::AgendaMethod::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_linesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_linesWriteSpeciesSplitXML(), ARTS::AgendaMethod::abs_linesWriteSplitXML(), ARTS::AgendaMethod::abs_speciesDefineAllInScenario(), ARTS::AgendaMethod::atm_fields_compactCreateFromField(), ARTS::AgendaMethod::AtmRawRead(), ARTS::AgendaMethod::CIAInfo(), ARTS::AgendaMethod::CIARecordReadFromFile(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::diameter_maxFromDiameter_volume_equ(), ARTS::AgendaMethod::diameter_volume_equFromDiameter_max(), ARTS::AgendaMethod::Error(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::ExtractFromMetaSingleScatSpecies(), ARTS::AgendaMethod::GetEnvironmentVariable(), ARTS::Method::GetEnvironmentVariable(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::Method::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::iyReplaceFromAux(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameter(), ARTS::AgendaMethod::jacobianAddScatSpecies(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameter(), ARTS::AgendaMethod::jacobianAddSpecialSpecies(), ARTS::AgendaMethod::jacobianAddSurfaceQuantity(), ARTS::AgendaMethod::MagRawRead(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::AgendaMethod::NumericFromVector(), ARTS::AgendaMethod::QuantumIdentifierSet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::retrievalAddCatalogParameter(), ARTS::AgendaMethod::retrievalAddScatSpecies(), ARTS::AgendaMethod::retrievalAddSpecialSpecies(), ARTS::AgendaMethod::retrievalAddSurfaceQuantity(), ARTS::AgendaMethod::ScatSpeciesPndAndScatAdd(), ARTS::AgendaMethod::StringSet(), ARTS::Method::StringSet(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::TessemNNReadAscii(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), ARTS::AgendaMethod::VectorExtractFromMatrix(), ARTS::AgendaMethod::vmr_fieldSetConstant(), ARTS::AgendaMethod::WindRawRead(), ARTS::AgendaMethod::WriteMolTau(), ARTS::AgendaMethod::ybatchMetProfiles(), ARTS::AgendaMethod::ybatchMetProfilesClear(), and ~String().
isnull()
bool ARTS::Var::String::isnull () const inline noexcept
Definition at line 1481 of file autoarts.h.
References v.
Referenced by ~String().
name()
const Group::String& ARTS::Var::String::name () const inline noexcept
Definition at line 1483 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
String& ARTS::Var::String::operator= (const type & t) inline noexcept
Definition at line 1479 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::String::pos () const inline noexcept
Definition at line 1480 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_cia_dataReadFromCIA(), ARTS::AgendaMethod::abs_lines_per_speciesReadSplitCatalog(), ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::AgendaMethod::abs_lines_per_speciesWriteSplitXML(), ARTS::AgendaMethod::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_linesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_linesWriteSpeciesSplitXML(), ARTS::AgendaMethod::abs_linesWriteSplitXML(), ARTS::AgendaMethod::abs_speciesDefineAllInScenario(), ARTS::AgendaMethod::atm_fields_compactCreateFromField(), ARTS::AgendaMethod::AtmRawRead(), ARTS::AgendaMethod::CIAInfo(), ARTS::AgendaMethod::CIARecordReadFromFile(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::diameter_maxFromDiameter_volume_equ(), ARTS::AgendaMethod::diameter_volume_equFromDiameter_max(), ARTS::AgendaMethod::Error(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::ExtractFromMetaSingleScatSpecies(), ARTS::AgendaMethod::GetEnvironmentVariable(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::iyReplaceFromAux(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameter(), ARTS::AgendaMethod::jacobianAddScatSpecies(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameter(), ARTS::AgendaMethod::jacobianAddSpecialSpecies(), ARTS::AgendaMethod::jacobianAddSurfaceQuantity(), ARTS::AgendaMethod::MagRawRead(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::AgendaMethod::NumericFromVector(), ARTS::AgendaMethod::QuantumIdentifierSet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::retrievalAddCatalogParameter(), ARTS::AgendaMethod::retrievalAddScatSpecies(), ARTS::AgendaMethod::retrievalAddSpecialSpecies(), ARTS::AgendaMethod::retrievalAddSurfaceQuantity(), ARTS::AgendaMethod::ScatSpeciesPndAndScatAdd(), ARTS::AgendaMethod::StringSet(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::TessemNNReadAscii(), ARTS::AgendaMethod::Touch(), ARTS::AgendaMethod::VectorExtractFromMatrix(), ARTS::AgendaMethod::vmr_fieldSetConstant(), ARTS::AgendaMethod::WindRawRead(), ARTS::AgendaMethod::WriteMolTau(), ARTS::AgendaMethod::ybatchMetProfiles(), and ARTS::AgendaMethod::ybatchMetProfilesClear().
value() [1/2]
const type& ARTS::Var::String::value () const inline noexcept
Definition at line 1478 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::String::value () inline noexcept
Definition at line 1477 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_cia_dataReadFromCIA(), ARTS::Method::abs_lines_per_speciesReadSplitCatalog(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesWriteSpeciesSplitXML(), ARTS::Method::abs_linesWriteSplitXML(), ARTS::Method::abs_speciesDefineAllInScenario(), ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::AtmRawRead(), ARTS::Method::CIAInfo(), ARTS::Method::CIARecordReadFromFile(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Method::Error(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::GetEnvironmentVariable(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), ARTS::Method::iyReplaceFromAux(), ARTS::Method::jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddShapeCatalogParameter(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::MagRawRead(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::NumericFromVector(), operator=(), ARTS::Method::QuantumIdentifierSet(), ARTS::Method::ReadNetCDF(), ARTS::Method::retrievalAddCatalogParameter(), ARTS::Method::retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ARTS::AgendaMethod::StringSet(), ARTS::Method::StringSet(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::TessemNNReadAscii(), ARTS::Method::Touch(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Method::WindRawRead(), ARTS::Method::WriteMolTau(), ARTS::Method::ybatchMetProfiles(), and ARTS::Method::ybatchMetProfilesClear().
Member Data Documentation
p
std::size_t ARTS::Var::String::p private
Definition at line 1470 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::String::v private
Definition at line 1471 of file autoarts.h.
Referenced by isnull(), value(), and ~String().
The documentation for this class was generated from the following file:
autoarts.h