ARTS: ARTS::Var::Index Class Reference
ARTS::Var::Index Class Reference
#include <autoarts.h>
Public Member Functions
Index () noexcept
Index (std::size_t i, void *x) noexcept
~Index () noexcept
Index (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
Index & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Index
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1216 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::Index::type = Group::Index private
Definition at line 1217 of file autoarts.h.
Constructor & Destructor Documentation
Index() [1/3]
ARTS::Var::Index::Index () inline noexcept
Definition at line 1221 of file autoarts.h.
Index() [2/3]
ARTS::Var::Index::Index (std::size_t i, void * x) inline noexcept
Definition at line 1222 of file autoarts.h.
~Index()
ARTS::Var::Index::~Index () inline noexcept
Definition at line 1223 of file autoarts.h.
References islast(), isnull(), and v.
Index() [3/3]
ARTS::Var::Index::Index (const type & val) inline noexcept
Definition at line 1224 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::Index::islast () const inline noexcept
Definition at line 1230 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::AgendaMethod::ArrayOfIndexLinSpace(), ARTS::AgendaMethod::ArrayOfIndexSetConstant(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::ExtractFromMetaSingleScatSpecies(), ARTS::AgendaMethod::ForLoop(), ARTS::AgendaMethod::GetEnvironmentVariable(), ARTS::Method::GetEnvironmentVariable(), ARTS::AgendaMethod::GetNumberOfThreads(), ARTS::Method::GetNumberOfThreads(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexAdd(), ARTS::Method::IndexAdd(), ARTS::AgendaMethod::IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexNumberOfAtmosphericPoints(), ARTS::AgendaMethod::IndexSet(), ARTS::Method::IndexSet(), ARTS::AgendaMethod::IndexStepDown(), ARTS::Method::IndexStepDown(), ARTS::AgendaMethod::IndexStepUp(), ARTS::Method::IndexStepUp(), ARTS::AgendaMethod::jacobianCalcPolyfit(), ARTS::AgendaMethod::jacobianCalcSinefit(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::AgendaMethod::SetNumberOfThreads(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), ARTS::AgendaMethod::VectorExtractFromMatrix(), ARTS::AgendaMethod::verbositySet(), ARTS::AgendaMethod::verbositySetAgenda(), ARTS::AgendaMethod::verbositySetFile(), ARTS::AgendaMethod::verbositySetScreen(), ARTS::AgendaMethod::ybatchMetProfiles(), ARTS::AgendaMethod::ybatchMetProfilesClear(), and ~Index().
isnull()
bool ARTS::Var::Index::isnull () const inline noexcept
Definition at line 1229 of file autoarts.h.
References v.
Referenced by ~Index().
name()
const Group::String& ARTS::Var::Index::name () const inline noexcept
Definition at line 1231 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
Index& ARTS::Var::Index::operator= (const type & t) inline noexcept
Definition at line 1227 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Index::pos () const inline noexcept
Definition at line 1228 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::AgendaMethod::ArrayOfIndexLinSpace(), ARTS::AgendaMethod::ArrayOfIndexSetConstant(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::ExtractFromMetaSingleScatSpecies(), ARTS::AgendaMethod::ForLoop(), ARTS::AgendaMethod::GetEnvironmentVariable(), ARTS::AgendaMethod::GetNumberOfThreads(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexAdd(), ARTS::AgendaMethod::IndexNumberOfAtmosphericPoints(), ARTS::AgendaMethod::IndexSet(), ARTS::AgendaMethod::IndexStepDown(), ARTS::AgendaMethod::IndexStepUp(), ARTS::AgendaMethod::jacobianCalcPolyfit(), ARTS::AgendaMethod::jacobianCalcSinefit(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::AgendaMethod::SetNumberOfThreads(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::Touch(), ARTS::AgendaMethod::VectorExtractFromMatrix(), ARTS::AgendaMethod::verbositySet(), ARTS::AgendaMethod::verbositySetAgenda(), ARTS::AgendaMethod::verbositySetFile(), ARTS::AgendaMethod::verbositySetScreen(), ARTS::AgendaMethod::ybatchMetProfiles(), and ARTS::AgendaMethod::ybatchMetProfilesClear().
value() [1/2]
const type& ARTS::Var::Index::value () const inline noexcept
Definition at line 1226 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::Index::value () inline noexcept
Definition at line 1225 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::ArrayOfIndexLinSpace(), ARTS::AgendaMethod::ArrayOfIndexSetConstant(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::ForLoop(), ARTS::Method::GetEnvironmentVariable(), ARTS::Method::GetNumberOfThreads(), ARTS::Method::Ignore(), ARTS::Method::IndexAdd(), ARTS::Method::IndexNumberOfAtmosphericPoints(), ARTS::AgendaMethod::IndexSet(), ARTS::Method::IndexSet(), ARTS::Method::IndexStepDown(), ARTS::Method::IndexStepUp(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::AgendaMethod::jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), ARTS::AgendaMethod::jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), ARTS::Method::MatrixCBR(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixSetConstant(), ARTS::Method::MatrixUnitIntensity(), operator=(), ARTS::Method::SetNumberOfThreads(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6SetConstant(), ARTS::Method::Tensor7SetConstant(), ARTS::Method::Touch(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorSetConstant(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::Method::verbositySet(), ARTS::Method::verbositySetAgenda(), ARTS::Method::verbositySetFile(), ARTS::Method::verbositySetScreen(), ARTS::Method::ybatchMetProfiles(), and ARTS::Method::ybatchMetProfilesClear().
Member Data Documentation
p
std::size_t ARTS::Var::Index::p private
Definition at line 1218 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::Index::v private
Definition at line 1219 of file autoarts.h.
Referenced by isnull(), value(), and ~Index().
The documentation for this class was generated from the following file:
autoarts.h