ARTS: ARTS::Var::Verbosity Class Reference
ARTS::Var::Verbosity Class Reference
#include <autoarts.h>
Public Member Functions
Verbosity () noexcept
Verbosity (std::size_t i, void *x) noexcept
~Verbosity () noexcept
Verbosity (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
Verbosity & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Verbosity
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1684 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::Verbosity::type = Group::Verbosity private
Definition at line 1685 of file autoarts.h.
Constructor & Destructor Documentation
Verbosity() [1/3]
ARTS::Var::Verbosity::Verbosity () inline noexcept
Definition at line 1689 of file autoarts.h.
Verbosity() [2/3]
ARTS::Var::Verbosity::Verbosity (std::size_t i, void * x) inline noexcept
Definition at line 1690 of file autoarts.h.
~Verbosity()
ARTS::Var::Verbosity::~Verbosity () inline noexcept
Definition at line 1691 of file autoarts.h.
References islast(), isnull(), and v.
Verbosity() [3/3]
ARTS::Var::Verbosity::Verbosity (const type & val) inline noexcept
Definition at line 1692 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::Verbosity::islast () const inline noexcept
Definition at line 1698 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~Verbosity().
isnull()
bool ARTS::Var::Verbosity::isnull () const inline noexcept
Definition at line 1697 of file autoarts.h.
References v.
Referenced by ~Verbosity().
name()
const Group::String& ARTS::Var::Verbosity::name () const inline noexcept
Definition at line 1699 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
Verbosity& ARTS::Var::Verbosity::operator= (const type & t) inline noexcept
Definition at line 1695 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Verbosity::pos () const inline noexcept
Definition at line 1696 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::Verbosity::value () const inline noexcept
Definition at line 1694 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::Verbosity::value () inline noexcept
Definition at line 1693 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_cia_dataReadFromCIA(), ARTS::Method::abs_lines_per_speciesReadSplitCatalog(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetCutoff(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimit(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeType(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroring(), ARTS::Method::abs_lines_per_speciesSetMirroringForMatch(), ARTS::Method::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalization(), ARTS::Method::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::Method::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulation(), ARTS::Method::abs_lines_per_speciesSetPopulationForMatch(), ARTS::Method::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetT0(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::abs_linesDeleteWithLines(), ARTS::Method::abs_linesRemoveBand(), ARTS::Method::abs_linesReplaceWithLines(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetCutoff(), ARTS::Method::abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetLinemixingLimit(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_linesSetLineShapeType(), ARTS::Method::abs_linesSetLineShapeTypeForMatch(), ARTS::Method::abs_linesSetMirroring(), ARTS::Method::abs_linesSetMirroringForMatch(), ARTS::Method::abs_linesSetNormalization(), ARTS::Method::abs_linesSetNormalizationForMatch(), ARTS::Method::abs_linesSetPopulation(), ARTS::Method::abs_linesSetPopulationForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetT0(), ARTS::Method::abs_linesSetT0ForMatch(), ARTS::Method::abs_linesSetZeemanCoefficients(), ARTS::Method::abs_linesWriteSpeciesSplitXML(), ARTS::Method::abs_linesWriteSplitXML(), ARTS::Method::abs_nlteFromRaw(), ARTS::Method::abs_speciesAdd(), ARTS::Method::abs_speciesDefineAllInScenario(), ARTS::Method::abs_speciesSet(), ARTS::Method::AddZaAa(), ARTS::Method::AgendaExecute(), ARTS::Method::AgendaExecuteExclusive(), ARTS::Method::ArrayOfAgendaExecute(), ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::ArrayOfIndexLinSpace(), ARTS::Method::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::ArrayOfStringSet(), ARTS::Method::atm_fields_compactCleanup(), ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::atm_fields_compactFromMatrix(), ARTS::Method::AtmRawRead(), ARTS::Method::backend_channel_responseFlat(), ARTS::Method::batch_atm_fields_compactCleanup(), ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::CIAInfo(), ARTS::Method::CIARecordReadFromFile(), ARTS::Method::cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudboxSetManually(), ARTS::Method::cloudboxSetManuallyAltitude(), ARTS::Method::complex_refr_indexConstant(), ARTS::Method::complex_refr_indexIceMatzler06(), ARTS::Method::complex_refr_indexIceWarren84(), ARTS::Method::complex_refr_indexWaterLiebe93(), ARTS::Method::Copy(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxSet(), ARTS::Method::covmatDiagonal(), ARTS::Method::Delete(), ARTS::Method::DiagonalMatrix(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Method::DiffZaAa(), ARTS::Method::doit_za_grid_optCalc(), ARTS::Method::Duration(), ARTS::Method::EnergyLevelMapSet(), ARTS::Method::Error(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::FlagOff(), ARTS::Method::FlagOn(), ARTS::Method::Flatten(), ARTS::Method::ForLoop(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Method::geo_posWherePpathPassesZref(), ARTS::Method::GetEnvironmentVariable(), ARTS::Method::GetNumberOfThreads(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), ARTS::Method::IndexAdd(), ARTS::Method::IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexSet(), ARTS::Method::IndexSetToLast(), ARTS::Method::IndexStepDown(), ARTS::Method::IndexStepUp(), ARTS::init(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Method::iyReplaceFromAux(), ARTS::Method::jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddShapeCatalogParameter(), ARTS::Method::jacobianAddShapeCatalogParameters(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::jacobianCalcPolyfit(), ARTS::Method::jacobianCalcSinefit(), ARTS::Method::jacobianFromTwoY(), ARTS::Method::jacobianFromYbatch(), ARTS::Method::jacobianSetAffineTransformation(), ARTS::Method::lat_gridFromRawField(), ARTS::Method::LocalTimeOffset(), ARTS::Method::lon_gridFromRawField(), ARTS::Method::MagRawRead(), ARTS::Method::Matrix1ColFromVector(), ARTS::Method::Matrix1RowFromVector(), ARTS::Method::Matrix2ColFromVectors(), ARTS::Method::Matrix2RowFromVectors(), ARTS::Method::Matrix3ColFromVectors(), ARTS::Method::Matrix3RowFromVectors(), ARTS::Method::MatrixAddScalar(), ARTS::Method::MatrixCBR(), ARTS::Method::MatrixCopySparse(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::MatrixFromCovarianceMatrix(), ARTS::Method::MatrixMatrixMultiply(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixScale(), ARTS::Method::MatrixSet(), ARTS::Method::MatrixSetConstant(), ARTS::Method::MatrixUnitIntensity(), ARTS::Method::MatrixVectorMultiply(), ARTS::Method::mc_antennaSetGaussian(), ARTS::Method::mc_antennaSetGaussianByFWHM(), ARTS::Method::nbooksGet(), ARTS::Method::ncolsGet(), ARTS::Method::nelemGet(), ARTS::Method::nlibrariesGet(), ARTS::Method::nlte_fieldFromRaw(), ARTS::Method::nlte_fieldRescalePopulationLevels(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), ARTS::Method::nshelvesGet(), ARTS::Method::NumericAdd(), ARTS::Method::NumericFromVector(), ARTS::Method::NumericInvScale(), ARTS::Method::NumericScale(), ARTS::Method::NumericSet(), ARTS::Method::nvitrinesGet(), operator=(), ARTS::Method::p_gridRefine(), ARTS::Method::particle_fieldCleanup(), ARTS::Method::PFromZSimple(), ARTS::Method::QuantumIdentifierSet(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::RationalAdd(), ARTS::Method::RationalInvScale(), ARTS::Method::RationalScale(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::refellipsoidForAzimuth(), ARTS::Method::refellipsoidOrbitPlane(), ARTS::Method::retrievalAddCatalogParameter(), ARTS::Method::retrievalAddCatalogParameters(), ARTS::Method::retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), ARTS::Method::rte_losSet(), ARTS::Method::rte_posSet(), ARTS::Method::rtp_nlteFromRaw(), ARTS::Method::ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesScatAndMetaRead(), ARTS::Method::Select(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_responseBackendFrequencySwitching(), ARTS::Method::SetNumberOfThreads(), ARTS::Method::Sleep(), ARTS::Method::SparseSparseMultiply(), ARTS::Method::StringSet(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_reflectivityFromGriddedField6(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surfaceSemiSpecularBy3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), ARTS::Method::TangentPointExtract(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::telsemSurfaceTypeLandSea(), ARTS::Method::Tensor3AddScalar(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), ARTS::Method::Tensor7Scale(), ARTS::Method::Tensor7SetConstant(), ARTS::Method::TessemNNReadAscii(), ARTS::Method::TestTessem(), ARTS::Method::time_gridOffset(), ARTS::Method::time_stampsSort(), ARTS::Method::timeOffset(), ARTS::Method::Touch(), ARTS::Method::transmittanceFromIy_aux(), ARTS::Method::VectorAddScalar(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::VectorFlip(), ARTS::Method::VectorInsertGridPoints(), ARTS::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Method::VectorMatrixMultiply(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorScale(), ARTS::Method::VectorSet(), ARTS::Method::VectorSetConstant(), ARTS::Method::VectorVectorMultiply(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::Method::vmr_fieldSetAllConstant(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Method::WindRawRead(), ARTS::Method::WriteMolTau(), ARTS::Method::ybatchMetProfiles(), ARTS::Method::ybatchMetProfilesClear(), ARTS::Method::ySimpleSpectrometer(), and ARTS::Method::ZFromPSimple().
Member Data Documentation
p
std::size_t ARTS::Var::Verbosity::p private
Definition at line 1686 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::Verbosity::v private
Definition at line 1687 of file autoarts.h.
Referenced by isnull(), value(), and ~Verbosity().
The documentation for this class was generated from the following file:
autoarts.h