ARTS: ARTS::Var::Matrix Class Reference
ARTS::Var::Matrix Class Reference
#include <autoarts.h>
Public Member Functions
Matrix () noexcept
Matrix (std::size_t i, void *x) noexcept
~Matrix () noexcept
Matrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
Matrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Matrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1252 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::Matrix::type = Group::Matrix private
Definition at line 1253 of file autoarts.h.
Constructor & Destructor Documentation
Matrix() [1/3]
ARTS::Var::Matrix::Matrix () inline noexcept
Definition at line 1257 of file autoarts.h.
Matrix() [2/3]
ARTS::Var::Matrix::Matrix (std::size_t i, void * x) inline noexcept
Definition at line 1258 of file autoarts.h.
~Matrix()
ARTS::Var::Matrix::~Matrix () inline noexcept
Definition at line 1259 of file autoarts.h.
References islast(), isnull(), and v.
Matrix() [3/3]
ARTS::Var::Matrix::Matrix (const type & val) inline noexcept
Definition at line 1260 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::Matrix::islast () const inline noexcept
Definition at line 1266 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::AddZaAa(), ARTS::Method::AddZaAa(), ARTS::AgendaMethod::atm_fields_compactFromMatrix(), ARTS::AgendaMethod::cloudbox_fieldSetConstPerFreq(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::covmat_seSet(), ARTS::AgendaMethod::covmat_sxSet(), ARTS::AgendaMethod::covmatDiagonal(), ARTS::Method::covmatDiagonal(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::DiagonalMatrix(), ARTS::Method::DiagonalMatrix(), ARTS::AgendaMethod::DiffZaAa(), ARTS::Method::DiffZaAa(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::Method::FieldFromGriddedField(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpSurfaceFieldToPosition(), ARTS::AgendaMethod::jacobianSetAffineTransformation(), ARTS::AgendaMethod::Matrix1ColFromVector(), ARTS::Method::Matrix1ColFromVector(), ARTS::AgendaMethod::Matrix1RowFromVector(), ARTS::Method::Matrix1RowFromVector(), ARTS::AgendaMethod::Matrix2ColFromVectors(), ARTS::Method::Matrix2ColFromVectors(), ARTS::AgendaMethod::Matrix2RowFromVectors(), ARTS::Method::Matrix2RowFromVectors(), ARTS::AgendaMethod::Matrix3ColFromVectors(), ARTS::Method::Matrix3ColFromVectors(), ARTS::AgendaMethod::Matrix3RowFromVectors(), ARTS::Method::Matrix3RowFromVectors(), ARTS::AgendaMethod::MatrixAddScalar(), ARTS::Method::MatrixAddScalar(), ARTS::AgendaMethod::MatrixCBR(), ARTS::Method::MatrixCBR(), ARTS::AgendaMethod::MatrixCopySparse(), ARTS::Method::MatrixCopySparse(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::AgendaMethod::MatrixFromCovarianceMatrix(), ARTS::Method::MatrixFromCovarianceMatrix(), ARTS::AgendaMethod::MatrixMatrixMultiply(), ARTS::Method::MatrixMatrixMultiply(), ARTS::AgendaMethod::MatrixPlanck(), ARTS::Method::MatrixPlanck(), ARTS::AgendaMethod::MatrixScale(), ARTS::Method::MatrixScale(), ARTS::AgendaMethod::MatrixSet(), ARTS::Method::MatrixSet(), ARTS::AgendaMethod::MatrixSetConstant(), ARTS::Method::MatrixSetConstant(), ARTS::AgendaMethod::MatrixUnitIntensity(), ARTS::Method::MatrixUnitIntensity(), ARTS::AgendaMethod::MatrixVectorMultiply(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::Method::Reduce(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), ARTS::AgendaMethod::VectorExtractFromMatrix(), ARTS::AgendaMethod::VectorMatrixMultiply(), and ~Matrix().
isnull()
bool ARTS::Var::Matrix::isnull () const inline noexcept
Definition at line 1265 of file autoarts.h.
References v.
Referenced by ~Matrix().
name()
const Group::String& ARTS::Var::Matrix::name () const inline noexcept
Definition at line 1267 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
Matrix& ARTS::Var::Matrix::operator= (const type & t) inline noexcept
Definition at line 1263 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Matrix::pos () const inline noexcept
Definition at line 1264 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::AddZaAa(), ARTS::AgendaMethod::atm_fields_compactFromMatrix(), ARTS::AgendaMethod::cloudbox_fieldSetConstPerFreq(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::covmat_seSet(), ARTS::AgendaMethod::covmat_sxSet(), ARTS::AgendaMethod::covmatDiagonal(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::DiagonalMatrix(), ARTS::AgendaMethod::DiffZaAa(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpSurfaceFieldToPosition(), ARTS::AgendaMethod::jacobianSetAffineTransformation(), ARTS::AgendaMethod::Matrix1ColFromVector(), ARTS::AgendaMethod::Matrix1RowFromVector(), ARTS::AgendaMethod::Matrix2ColFromVectors(), ARTS::AgendaMethod::Matrix2RowFromVectors(), ARTS::AgendaMethod::Matrix3ColFromVectors(), ARTS::AgendaMethod::Matrix3RowFromVectors(), ARTS::AgendaMethod::MatrixAddScalar(), ARTS::AgendaMethod::MatrixCBR(), ARTS::AgendaMethod::MatrixCopySparse(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::AgendaMethod::MatrixFromCovarianceMatrix(), ARTS::AgendaMethod::MatrixMatrixMultiply(), ARTS::AgendaMethod::MatrixPlanck(), ARTS::AgendaMethod::MatrixScale(), ARTS::AgendaMethod::MatrixSet(), ARTS::AgendaMethod::MatrixSetConstant(), ARTS::AgendaMethod::MatrixUnitIntensity(), ARTS::AgendaMethod::MatrixVectorMultiply(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::Select(), ARTS::AgendaMethod::sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::AgendaMethod::Touch(), ARTS::AgendaMethod::VectorExtractFromMatrix(), and ARTS::AgendaMethod::VectorMatrixMultiply().
value() [1/2]
const type& ARTS::Var::Matrix::value () const inline noexcept
Definition at line 1262 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::Matrix::value () inline noexcept
Definition at line 1261 of file autoarts.h.
References v.
Referenced by ARTS::Method::AddZaAa(), ARTS::Method::atm_fields_compactFromMatrix(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), ARTS::Method::Copy(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_sxSet(), ARTS::Method::covmatDiagonal(), ARTS::Method::Delete(), ARTS::Method::DiagonalMatrix(), ARTS::Method::DiffZaAa(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Method::jacobianSetAffineTransformation(), ARTS::Method::Matrix1ColFromVector(), ARTS::Method::Matrix1RowFromVector(), ARTS::Method::Matrix2ColFromVectors(), ARTS::Method::Matrix2RowFromVectors(), ARTS::Method::Matrix3ColFromVectors(), ARTS::Method::Matrix3RowFromVectors(), ARTS::Method::MatrixAddScalar(), ARTS::Method::MatrixCBR(), ARTS::Method::MatrixCopySparse(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::MatrixFromCovarianceMatrix(), ARTS::Method::MatrixMatrixMultiply(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixScale(), ARTS::AgendaMethod::MatrixSet(), ARTS::Method::MatrixSet(), ARTS::Method::MatrixSetConstant(), ARTS::Method::MatrixUnitIntensity(), ARTS::Method::MatrixVectorMultiply(), ARTS::Method::ncolsGet(), ARTS::Method::nrowsGet(), operator=(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::Select(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::Touch(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::VectorMatrixMultiply(), ARTS::Method::VectorZtanToZa1D(), and ARTS::Method::VectorZtanToZaRefr1D().
Member Data Documentation
p
std::size_t ARTS::Var::Matrix::p private
Definition at line 1254 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::Matrix::v private
Definition at line 1255 of file autoarts.h.
Referenced by isnull(), value(), and ~Matrix().
The documentation for this class was generated from the following file:
autoarts.h