ARTS: ARTS::Var::Numeric Class Reference
ARTS::Var::Numeric Class Reference
#include <autoarts.h>
Public Member Functions
Numeric () noexcept
Numeric (std::size_t i, void *x) noexcept
~Numeric () noexcept
Numeric (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
Numeric & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Numeric
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1270 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::Numeric::type = Group::Numeric private
Definition at line 1271 of file autoarts.h.
Constructor & Destructor Documentation
Numeric() [1/3]
ARTS::Var::Numeric::Numeric () inline noexcept
Definition at line 1275 of file autoarts.h.
Numeric() [2/3]
ARTS::Var::Numeric::Numeric (std::size_t i, void * x) inline noexcept
Definition at line 1276 of file autoarts.h.
~Numeric()
ARTS::Var::Numeric::~Numeric () inline noexcept
Definition at line 1277 of file autoarts.h.
References islast(), isnull(), and v.
Numeric() [3/3]
ARTS::Var::Numeric::Numeric (const type & val) inline noexcept
Definition at line 1278 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::Numeric::islast () const inline noexcept
Definition at line 1284 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoff(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimit(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForSpecies(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_linesSetCutoff(), ARTS::AgendaMethod::abs_linesSetCutoffForMatch(), ARTS::AgendaMethod::abs_linesSetLinemixingLimit(), ARTS::AgendaMethod::abs_linesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_linesSetT0(), ARTS::AgendaMethod::abs_linesSetT0ForMatch(), ARTS::AgendaMethod::atm_fields_compactCleanup(), ARTS::AgendaMethod::backend_channel_responseFlat(), ARTS::AgendaMethod::batch_atm_fields_compactCleanup(), ARTS::AgendaMethod::cloudboxSetManually(), ARTS::AgendaMethod::cloudboxSetManuallyAltitude(), ARTS::AgendaMethod::complex_refr_indexConstant(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::AgendaMethod::diameter_volume_equFromDiameter_max(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::AgendaMethod::doit_za_grid_optCalc(), ARTS::AgendaMethod::Duration(), ARTS::Method::Duration(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::AgendaMethod::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::AgendaMethod::FrequencyFromWavelength(), ARTS::Method::FrequencyFromWavelength(), ARTS::AgendaMethod::geo_posWherePpathPassesZref(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpAtmFieldToPosition(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::AgendaMethod::InterpGriddedField2ToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::AgendaMethod::InterpSurfaceFieldToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::AgendaMethod::jacobianFromTwoY(), ARTS::AgendaMethod::jacobianFromYbatch(), ARTS::AgendaMethod::LocalTimeOffset(), ARTS::Method::LocalTimeOffset(), ARTS::AgendaMethod::MatrixAddScalar(), ARTS::AgendaMethod::MatrixPlanck(), ARTS::AgendaMethod::MatrixScale(), ARTS::AgendaMethod::MatrixSetConstant(), ARTS::AgendaMethod::mc_antennaSetGaussian(), ARTS::AgendaMethod::mc_antennaSetGaussianByFWHM(), ARTS::AgendaMethod::nlte_fieldRescalePopulationLevels(), ARTS::AgendaMethod::NumericAdd(), ARTS::Method::NumericAdd(), ARTS::AgendaMethod::NumericFromVector(), ARTS::Method::NumericFromVector(), ARTS::AgendaMethod::NumericInvScale(), ARTS::Method::NumericInvScale(), ARTS::AgendaMethod::NumericScale(), ARTS::Method::NumericScale(), ARTS::AgendaMethod::NumericSet(), ARTS::Method::NumericSet(), ARTS::AgendaMethod::p_gridRefine(), ARTS::AgendaMethod::particle_fieldCleanup(), ARTS::AgendaMethod::Reduce(), ARTS::Method::Reduce(), ARTS::AgendaMethod::refellipsoidForAzimuth(), ARTS::AgendaMethod::refellipsoidOrbitPlane(), ARTS::AgendaMethod::rte_losSet(), ARTS::AgendaMethod::rte_posSet(), ARTS::AgendaMethod::sensor_responseBackendFrequencySwitching(), ARTS::AgendaMethod::surfaceSemiSpecularBy3beams(), ARTS::AgendaMethod::surfaceSplitSpecularTo3beams(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::AgendaMethod::Tensor3AddScalar(), ARTS::AgendaMethod::Tensor3Scale(), ARTS::AgendaMethod::Tensor3SetConstant(), ARTS::AgendaMethod::Tensor4AddScalar(), ARTS::AgendaMethod::Tensor4Scale(), ARTS::AgendaMethod::Tensor4SetConstant(), ARTS::AgendaMethod::Tensor5Scale(), ARTS::AgendaMethod::Tensor5SetConstant(), ARTS::AgendaMethod::Tensor6Scale(), ARTS::AgendaMethod::Tensor6SetConstant(), ARTS::AgendaMethod::Tensor7Scale(), ARTS::AgendaMethod::Tensor7SetConstant(), ARTS::AgendaMethod::time_gridOffset(), ARTS::AgendaMethod::timeOffset(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), ARTS::AgendaMethod::VectorAddScalar(), ARTS::AgendaMethod::VectorLinSpace(), ARTS::AgendaMethod::VectorLogSpace(), ARTS::AgendaMethod::VectorNLinSpace(), ARTS::AgendaMethod::VectorNLogSpace(), ARTS::AgendaMethod::VectorScale(), ARTS::AgendaMethod::VectorSetConstant(), ARTS::AgendaMethod::vmr_fieldSetConstant(), ARTS::AgendaMethod::ySimpleSpectrometer(), and ~Numeric().
isnull()
bool ARTS::Var::Numeric::isnull () const inline noexcept
Definition at line 1283 of file autoarts.h.
References v.
Referenced by ~Numeric().
name()
const Group::String& ARTS::Var::Numeric::name () const inline noexcept
Definition at line 1285 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
Numeric& ARTS::Var::Numeric::operator= (const type & t) inline noexcept
Definition at line 1281 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Numeric::pos () const inline noexcept
Definition at line 1282 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoff(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimit(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForSpecies(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_linesSetCutoff(), ARTS::AgendaMethod::abs_linesSetCutoffForMatch(), ARTS::AgendaMethod::abs_linesSetLinemixingLimit(), ARTS::AgendaMethod::abs_linesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_linesSetT0(), ARTS::AgendaMethod::abs_linesSetT0ForMatch(), ARTS::AgendaMethod::atm_fields_compactCleanup(), ARTS::AgendaMethod::backend_channel_responseFlat(), ARTS::AgendaMethod::batch_atm_fields_compactCleanup(), ARTS::AgendaMethod::cloudboxSetManually(), ARTS::AgendaMethod::cloudboxSetManuallyAltitude(), ARTS::AgendaMethod::complex_refr_indexConstant(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::diameter_maxFromDiameter_volume_equ(), ARTS::AgendaMethod::diameter_volume_equFromDiameter_max(), ARTS::AgendaMethod::doit_za_grid_optCalc(), ARTS::AgendaMethod::Duration(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::FrequencyFromCGSAngularWavenumber(), ARTS::AgendaMethod::FrequencyFromCGSKayserWavenumber(), ARTS::AgendaMethod::FrequencyFromWavelength(), ARTS::AgendaMethod::geo_posWherePpathPassesZref(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpAtmFieldToPosition(), ARTS::AgendaMethod::InterpGriddedField2ToPosition(), ARTS::AgendaMethod::InterpSurfaceFieldToPosition(), ARTS::AgendaMethod::jacobianFromTwoY(), ARTS::AgendaMethod::jacobianFromYbatch(), ARTS::AgendaMethod::LocalTimeOffset(), ARTS::AgendaMethod::MatrixAddScalar(), ARTS::AgendaMethod::MatrixPlanck(), ARTS::AgendaMethod::MatrixScale(), ARTS::AgendaMethod::MatrixSetConstant(), ARTS::AgendaMethod::mc_antennaSetGaussian(), ARTS::AgendaMethod::mc_antennaSetGaussianByFWHM(), ARTS::AgendaMethod::nlte_fieldRescalePopulationLevels(), ARTS::AgendaMethod::NumericAdd(), ARTS::AgendaMethod::NumericFromVector(), ARTS::AgendaMethod::NumericInvScale(), ARTS::AgendaMethod::NumericScale(), ARTS::AgendaMethod::NumericSet(), ARTS::AgendaMethod::p_gridRefine(), ARTS::AgendaMethod::particle_fieldCleanup(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::refellipsoidForAzimuth(), ARTS::AgendaMethod::refellipsoidOrbitPlane(), ARTS::AgendaMethod::rte_losSet(), ARTS::AgendaMethod::rte_posSet(), ARTS::AgendaMethod::sensor_responseBackendFrequencySwitching(), ARTS::AgendaMethod::surfaceSemiSpecularBy3beams(), ARTS::AgendaMethod::surfaceSplitSpecularTo3beams(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::AgendaMethod::Tensor3AddScalar(), ARTS::AgendaMethod::Tensor3Scale(), ARTS::AgendaMethod::Tensor3SetConstant(), ARTS::AgendaMethod::Tensor4AddScalar(), ARTS::AgendaMethod::Tensor4Scale(), ARTS::AgendaMethod::Tensor4SetConstant(), ARTS::AgendaMethod::Tensor5Scale(), ARTS::AgendaMethod::Tensor5SetConstant(), ARTS::AgendaMethod::Tensor6Scale(), ARTS::AgendaMethod::Tensor6SetConstant(), ARTS::AgendaMethod::Tensor7Scale(), ARTS::AgendaMethod::Tensor7SetConstant(), ARTS::AgendaMethod::time_gridOffset(), ARTS::AgendaMethod::timeOffset(), ARTS::AgendaMethod::Touch(), ARTS::AgendaMethod::VectorAddScalar(), ARTS::AgendaMethod::VectorLinSpace(), ARTS::AgendaMethod::VectorLogSpace(), ARTS::AgendaMethod::VectorNLinSpace(), ARTS::AgendaMethod::VectorNLogSpace(), ARTS::AgendaMethod::VectorScale(), ARTS::AgendaMethod::VectorSetConstant(), ARTS::AgendaMethod::vmr_fieldSetConstant(), and ARTS::AgendaMethod::ySimpleSpectrometer().
value() [1/2]
const type& ARTS::Var::Numeric::value () const inline noexcept
Definition at line 1280 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::Numeric::value () inline noexcept
Definition at line 1279 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetCutoff(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimit(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::Method::abs_lines_per_speciesSetT0(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetCutoff(), ARTS::Method::abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetLinemixingLimit(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_linesSetT0(), ARTS::Method::abs_linesSetT0ForMatch(), ARTS::Method::atm_fields_compactCleanup(), ARTS::Method::backend_channel_responseFlat(), ARTS::Method::batch_atm_fields_compactCleanup(), ARTS::Method::cloudboxSetManually(), ARTS::Method::cloudboxSetManuallyAltitude(), ARTS::Method::complex_refr_indexConstant(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Method::doit_za_grid_optCalc(), ARTS::Method::Duration(), ARTS::Method::Extract(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Method::geo_posWherePpathPassesZref(), ARTS::Method::Ignore(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Method::jacobianFromTwoY(), ARTS::Method::jacobianFromYbatch(), ARTS::Method::LocalTimeOffset(), ARTS::Method::MatrixAddScalar(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixScale(), ARTS::Method::MatrixSetConstant(), ARTS::Method::mc_antennaSetGaussian(), ARTS::Method::mc_antennaSetGaussianByFWHM(), ARTS::Method::nlte_fieldRescalePopulationLevels(), ARTS::Method::NumericAdd(), ARTS::Method::NumericFromVector(), ARTS::Method::NumericInvScale(), ARTS::Method::NumericScale(), ARTS::AgendaMethod::NumericSet(), ARTS::Method::NumericSet(), operator=(), ARTS::Method::p_gridRefine(), ARTS::Method::particle_fieldCleanup(), ARTS::Method::Reduce(), ARTS::Method::refellipsoidForAzimuth(), ARTS::Method::refellipsoidOrbitPlane(), ARTS::Method::rte_losSet(), ARTS::Method::rte_posSet(), ARTS::Method::sensor_responseBackendFrequencySwitching(), ARTS::Method::surfaceSemiSpecularBy3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::Tensor3AddScalar(), ARTS::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), ARTS::Method::Tensor7Scale(), ARTS::Method::Tensor7SetConstant(), ARTS::Method::time_gridOffset(), ARTS::Method::timeOffset(), ARTS::Method::Touch(), ARTS::Method::VectorAddScalar(), ARTS::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorScale(), ARTS::Method::VectorSetConstant(), ARTS::Method::vmr_fieldSetConstant(), and ARTS::Method::ySimpleSpectrometer().
Member Data Documentation
p
std::size_t ARTS::Var::Numeric::p private
Definition at line 1272 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::Numeric::v private
Definition at line 1273 of file autoarts.h.
Referenced by isnull(), value(), and ~Numeric().
The documentation for this class was generated from the following file:
autoarts.h